export const users = [
  {
    id: 1,
    name: 'John Doe',
    email: 'john@example.com',
    role: 'Developer',
    plan: 'Basic',
  },
  {
    id: 2,
    name: 'Jane Smith',
    email: 'jane@example.com',
    role: 'Designer',
    plan: 'Premium',
  },
  {
    id: 3,
    name: 'Alice Johnson',
    email: 'alice@example.com',
    role: 'Product Manager',
    plan: 'Basic',
  },
  {
    id: 4,
    name: 'Bob Brown',
    email: 'bob@example.com',
    role: 'Developer',
    plan: 'Basic',
  },
  {
    id: 5,
    name: 'Carol White',
    email: 'carol@example.com',
    role: 'Designer',
    plan: 'Premium',
  },
  {
    id: 6,
    name: 'David Green',
    email: 'david@example.com',
    role: 'Product Manager',
    plan: 'Premium',
  },
  {
    id: 7,
    name: 'Eve Black',
    email: 'eve@example.com',
    role: 'Developer',
    plan: 'Basic',
  },
  {
    id: 8,
    name: 'Frank Grey',
    email: 'frank@example.com',
    role: 'Designer',
    plan: 'Basic',
  },
  {
    id: 9,
    name: 'Grace Blue',
    email: 'grace@example.com',
    role: 'Product Manager',
    plan: 'Premium',
  },
  {
    id: 10,
    name: 'Hank Red',
    email: 'hank@example.com',
    role: 'Developer',
    plan: 'Basic',
  },
  {
    id: 11,
    name: 'Ivy Yellow',
    email: 'ivy@example.com',
    role: 'Designer',
    plan: 'Premium',
  },
  {
    id: 12,
    name: 'Jack Orange',
    email: 'jack@example.com',
    role: 'Product Manager',
    plan: 'Basic',
  },
  {
    id: 13,
    name: 'Kathy Violet',
    email: 'kathy@example.com',
    role: 'Developer',
    plan: 'Premium',
  },
  {
    id: 14,
    name: 'Leo Pink',
    email: 'leo@example.com',
    role: 'Designer',
    plan: 'Basic',
  },
] as const;
